spring.application.name=ATM-Simulator


# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/atm_simulator
spring.datasource.username=yodishtrvythilingum
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver


# Spring JPA configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# server port connection
server.port=8080


